### ISSUE TITLE
Where does the compiled css go?

### ISSUE THREAD

**Issue by jcobb** [wGEric/Komodo-LESS#1]
I've just installed the extension on Komodo Edit, version 6.1.3. The extension seems to work fine, I can selected 'Compile Saved File in to CSS' and the console informs me that it is indeed compiling it - however I can not find where the compiled css ends up.

**Comment by wGEric** [comment]
It is suppose to be in the same folder as the .less file. Also the console should tell you where it was saved.

**Comment by art0rz** [comment]
Also having this problem. It does not spit out any errors nor does it create a .css file. It simply tells me "[LESS] Compiling LESS file" in the console.
